name: Docker Image Build
on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: list of files
        run: ls -la

      - name: Check go version
        run: go version

      - name: Run Unit Test
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aditirvan/myapp-golang:${{ github.run_number }}

      - name: Check docker images
        run: docker image ls

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-push
  #   steps:
  #     - name: privisioning server
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_KEY }}
  #         port: 22
  #         script: |
  #           docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
  #           docker pull aditirvan/myapp-golang:${{ github.run_number }}
  #           docker rm -f myapp
  #           docker run --name myapp -d -p 80:8060 aditirvan/myapp-golang:${{ github.run_number }}

